fix(ci): use current repo name

diff --git a/.github/workflows/build-desktop-release.yml b/.github/workflows/build-desktop-release.yml
--- a/.github/workflows/build-desktop-release.yml
+++ b/.github/workflows/build-desktop-release.yml
@@ -109,8 +109,11 @@ jobs:
 
       - name: Do Not Overwrite Existing Release
         if: ${{ github.event.inputs.build-target == 'beta' }}
-        run:
-          curl -f "https://api.github.com/repos/${{ github.repository }}/releases/tag/${{ steps.ref.outputs.version }}" && exit 1
+        run: |
+          if curl -f "https://api.github.com/repos/${{ github.repository }}/releases/tag/${{ steps.ref.outputs.version }}"; then
+            echo "::error Release already exists"
+            exit 1
+          fi
 
       - name: Update Nightly APP Version
         if: ${{ github.event.inputs.build-target == 'nightly' || github.event_name == 'schedule' }}
